from keyboards.action_kb import action_kb
from keyboards.categories_kb import categories_kb
from keyboards.subject_categories.humanitarian import humanitarian_kb
from keyboards.subject_categories.natural_sci_kb import natural_sci_kb
from keyboards.subject_categories.technical_kb import technical_kb
from keyboards.subject_categories.social_sci_kb import social_sci_kb
from keyboards.add_olympiad_kb import get_add_olympiad_kb
from keyboards.remove_olympiad_kb import get_remove_olympiad_kb